var $j=jQuery.noConflict();function postImageHover(){$j('.blog_teasers:not(.masonry_blocks) .post_teaser_img, a.prettyPhoto img, a .teaser_grid_img, .gallery-item .attachment-thumbnail').attr({"title":" "}).hover(function(){$j(this).stop().animate({"opacity":0.7},300);},function(){$j(this).stop().animate({"opacity":1},300);});}
function portfolioSortable(){jQuery('.wpb_sort li a.wpb_sortable_cats').click(function(e){e.preventDefault();var classname=jQuery(this).attr('data-value');jQuery('.wpb_sortable_current').removeClass('wpb_sortable_current');jQuery(this).addClass('wpb_sortable_current');jQuery('.wpb_sortable').stop().animate({"opacity":1});jQuery('.wpb_sortable:not(.'+classname+')').stop().animate({"opacity":0.2});});jQuery('.wpb_sort li.wpb_all_cats a').click(function(e){e.preventDefault();jQuery('.wpb_sortable_current').removeClass('wpb_sortable_current');jQuery(this).addClass('wpb_sortable_current');jQuery('.wpb_sortable').stop().animate({"opacity":1});});}
function homeMenuInit(){var delay=100;$j('.header_menu > li').each(function(index){$j(this).delay(delay*index+1500).animate({"left":0});});}
function menuBehaviour(){jQuery(".header_menu").children('li').children('.sub-menu').css({"display":"none"});jQuery(".header_menu li a").removeAttr('title');jQuery(".header_menu").children('li').each(function(){var sublist=jQuery(this).children('.sub-menu');jQuery(this).hover(function(){jQuery(this).addClass('hover');if(sublist.length>0){jQuery(this).addClass('hover_triangle');}
var new_l=jQuery(this).find('a').outerWidth()+ 1;sublist.stop().css({height:"auto",overflow:"hidden",display:"block",opacity:0,left:new_l}).animate({opacity:1},400,function(){});},function(){jQuery(this).removeClass('hover hover_triangle');sublist.stop().animate({opacity:0},400,function(){$j(this).css({display:"none",overflow:"hidden"});});});});}
function masonryTeasers(){jQuery('.float_blocks_container .masonry_blocks').masonry({itemSelector:'.float_block',columnWidth:1,gutterWidth:0});}
function inputBehaviour(){$j("input:text, textarea").each(function(){$j(this).attr({"rel":$j(this).val()});$j(this).focus(function(){if($j(this).val()==$j(this).attr('rel')){$j(this).val('');}
$j(this).addClass("focus");}).blur(function(){if($j(this).val()==''){$j(this).val($j(this).attr('rel'));}else{$j(this).addClass("notempty");}
$j(this).removeClass("focus");});});}
function vc_prettyPhoto(){try{jQuery('a.prettyphoto, .gallery-icon a[href*=".jpg"], a[rel^="prettyPhoto"], a.prettyPhoto, .gallery a, #slider .prettyphoto a').prettyPhoto({animationSpeed:'normal',padding:15,opacity:0.7,showTitle:true,allowresize:true,counter_separator_label:'/',theme:'dark_square',hideflash:false,modal:false,callback:function(){var url=location.href;var hashtag=(url.indexOf('#!prettyPhoto'))?true:false;if(hashtag)location.hash="!";},social_tools:''});}catch(err){}}
function initJsSweetness(){if(blockrc=='true'){$j(this).bind("contextmenu",function(e){e.preventDefault();});}
menuBehaviour();inputBehaviour();postImageHover();portfolioSortable();$j('.content_holder, #supersized').css({"opacity":0});masonryTeasers();$j('.main_content table tr:even').addClass('even');$j('#search_ico').toggle(function(){$j('#header #searchform').fadeIn();},function(){$j('#header #searchform').fadeOut();});}
jQuery(document).ready(function($j){initJsSweetness();});jQuery(window).load(function(){masonryTeasers();homeMenuInit();$j('.content_holder, #supersized').animate({"opacity":1},800);var correct_w=0;$j('#thumb-list li').each(function(index){correct_w+=$j(this).outerWidth(true);});$j('#thumb-list').width(correct_w);});(function($j){var userAgent=navigator.userAgent.toLowerCase();$j.browser={version:(userAgent.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,'0'])[1],safari:/webkit/.test(userAgent),opera:/opera/.test(userAgent),msie:/msie/.test(userAgent)&&!/opera/.test(userAgent),mozilla:/mozilla/.test(userAgent)&&!/(compatible|webkit)/.test(userAgent)};})(jQuery);